#!/bin/bash

echo "Installing fbset package, requires root privileges.."
sudo apt-get install fbset

echo "Please compile lock_screen.c using gcc "
echo "After compiling use this app as     ./a.out /dev/input/event0 "
